# Generated by Django 5.2.14 on 2026-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fighters/'),
        ),
    ]
