# Generated by Django 5.2.14 on 2026-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='country',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
