# Generated by Django 5.2.14 on 2026-06-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_fighters', '0002_fighter_country_fighter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(max_length=255),
        ),
    ]
