# Generated by Django 5.2.14 on 2026-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_fighters', '0002_fighter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
